config/routes.rb
Cotizar::Application.routes.draw do

  resources :cars
  resources :computers do
    collection do
      post 'index'
      get 'alternative_new' #metodo alternativo de ingreso de computadores
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  match 'computers/:id/edit' => 'computers#edit'

  resources :televisions do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  
  resources :main
  resources :smartphones do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
    end
  end

  
  
  
  get "cars/index"
  match 'cars/save' => 'cars#save'
  match 'cars/delete' => 'cars#delete'
  match 'cars/edit' => 'cars#edit'
  match 'cars/new' => 'cars#new'
  match 'cars/update' => 'cars#update'
  match 'cars/search' => 'cars#search'
  get "main/index"

  
  root :to => 'main#index'

end

app/models/smartphone.rb
class Smartphone < ActiveRecord::Base
  attr_accessible :img_ref, :modelo, :precio
  
  attr_accessible :proce_num_cores, :proce_speed, :almacenamiento
  
  attr_accessible :cam_resolution, :cam_front_resolution, :cam_autofoco
  
  attr_accessible :dim_alto, :dim_ancho, :dim_prof, :dim_peso
  
  attr_accessible :battery_capacity, :battery_usb_recargable, :battery_wireless_rechargable
  
  belongs_to :marca
  belongs_to :display_tech
  belongs_to :display_depth
  belongs_to :display_size
  belongs_to :display_resolution
  belongs_to :marca_procesador
  belongs_to :sistema_operativo
  belongs_to :cam_flash
  
  has_many :map_smartphone_reds  
  has_many :reds, through: :map_smartphone_reds
  
  has_many :map_smartphone_sensors
  has_many :smartphone_sensors, through: :map_smartphone_sensors
  
  has_many :map_smartphone_connectors
  has_many :smartphone_connectors, through: :map_smartphone_connectors  
  
  #####################################################################################################################
  #atrr_accessible :sen_acelerometro, :sen_geomagnetico, :sen_giroscopio, :sen_rgb, :sen_gestos
  #attr_accessible :sen_temperatura, :sen_barometro, :sen_humedad
  
  #attr_accessible :net_2g_edge, :net_3g, :net_4g, :net_wifi, :net_wifi_direct, :bluetooth, :net_prox_nfc, :net_pc_sync
  
  #attr_accessible :conn_usb, :conn_audifonos, :conn_mem_externa, :conn_sim, :conn_cel_conn, :conn_mhl
  
  #attr_accessible :geolocalizacion
end

app/controllers/smartphones_controller.rb
class SmartphonesController < ApplicationController
  #layout 'products_layout'
  
  def index
    @smartphones = Smartphone.find(:all)
    session[:compare_category] = 'smartphones'
    session[:selected_items] ||= []
    render :search
  end
  
  def show
    @smartphone = Smartphone.find(params[:id])

    #Lista de imagenes correspondientes a un producto
    #se considera un default de 4 imagenes por producto
    @image_paths = []
    marca = Marca.find(@smartphone.marca_id).nombre_marca
    modelo = @smartphone.modelo.upcase
    (1..4).each do |image|
      img_path = 'smartphone_images/'+marca+'/'+modelo+'/'+image.to_s+'.jpg'
      if File.exist?(Rails.root.join('app','assets','images', img_path))
        @image_paths << img_path
      end
    end
  end
  
  def select_for_compare    
    params[:product].each do |product|
      action, id = product.split('-')
      
      if session[:compare_category] != 'smartphones'
        session[:compare_category] = 'smartphones'
        session.delete(:selected_items)
      end
          
      case action
        when 'a'
          (session[:selected_items] ||= []) << Smartphone.find(:first, :select => 'id, img_ref, marca_id, modelo, precio', :conditions => {:id => id})#id.to_i
        when 'd'
          if session[:selected_items].nil?
            session[:selected_items] = []
          else
            session[:selected_items].delete_if{|x| x.id == id.to_i}
          end
      end
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  def compare
    @selected_items = []
    
    @items_to_compare = params[:compare_items].length
    
    params[:compare_items].each do |item|
      @selected_items << Smartphone.find(:first, :conditions => {:id => item})
    end
  end

  def new
    if params[:marca]
      @smartphones = Smartphone.find(:all, :conditions => {:marca_id => params[:marca_id][:value]})
    else
      @smartphones = Smartphone.find(:all)
    end
    @smartphones = Smartphone.new # Nuevo registro a ingresar    
  end
  
  def search # esta funcion rq hay que cambiarla entera, para adecuarla a la especificidad de smartphones
    #FILTRO POR SISTEMA OPERATIVO (Check box, change)
    if params[:search][:os_all] == '1'
      @smartphones = Smartphone.find(:all) 
      #@smartphones.select{|s| s.sistema_operativo_id.to_s == params[:search][:sistema_operativo_id]}
    else
      @smartphones = []
      if [:params][:os_android] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
      if [:params][:os_blackberry] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
      if [:params][:os_ios] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
      if [:params][:os_symbian] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
      if [:params][:os_win_mob] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
      if [:params][:os_win_ph] == '1'
        @smartphones = (@smartphones + Smartphone.find(:all, :conditions => {:sistema_operativo_id => 'TO BE'}))
      end
    end        
    
    #FILTRO POR MARCA (drop down list, ok)
    if params[:search][:marca_id] != ""
      @smartphones = @smartphones.select{|s| s.marca_id.to_s == params[:search][:marca_id]}
    end
    
    #FILTRO POR TAMAÑO DE PANTALLA (esto lo quiero hacer con slider asi que habra que cambiarlo)
    if params[:search][:screen_size] != ""
      @smartphones = @smartphones.select{|s| s.display_size_id.to_s == params[:search][:screen_size]}
    end
    
    #FILTRO POR CALDAD DE CAMARA (esto lo qiuero hacer con slider asi que habra que cambiarlo)
    if params[:search][:camara_q] != ""
      @smartphones = @smartphones.select{|s| s.cam_resolution.to_s == params[:search][:camara_q]}
    end
    
    #FILTRO POR REDES
    @smart_2g = []
    @smart_3g = []
    @smart_4g = []
    #AGREGAR MAS EVENTUALMENTE
    if params[:search][:net_all] == '1'
      #aca no se hace nadita
    else
      if params[:search][:net_2g] == '1'
        red_2g = Red.find(:all, :conditions => {:nombre => "3g"})
        @smart_2g = red_2g.smartphones.all
      end
      if params[:search][:net_3g] == '1'
        red_3g = Red.find(:all, :conditions => {:nombre => "TO BE"})
        @smart_3g = red_3g.smartphones.all
      end
      if params[:search][:net_4g] == '1'
        red_4g = Red.find(:all, :conditions => {:nombre => "TO BE"})
        @smart_4g = red_4g.smartphones.all
      end
      #ACA HAY QUE PONER EL RESTO DE LAS REDES EVENTUALMENTE
      @smartphones = @smart_2g + @smart_3g + @smart_4g
    end    
    
    respond_to do |format|
      format.js #search.js.erb
    end
  end
  
  def create
    @smartphone = Smartphone.new(params[:smartphone])
    
    if @smartphone.save
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end
  
  def edit
    @smartphone = Smartphone.find(params[:id])
  end
  
  def update
    @smartphone = Smartphone.find(params[:id])
    if @smartphone.update_attributes(params[:smartphone])
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end
  
  def destroy
    if Smartphone.destroy(params[:id])
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end
end

app/helpers/smartphones_helper.rb
module SmartphonesHelper
end

app/views/smartphones/_compare_list_marks.html.erb
<div id="compare-list-marks">
	<p>(<%= session[:selected_items].length %>) Productos</p>
	<table>
		<tr>
			<% session[:selected_items].each do |item|%>
					<%= hidden_field_tag 'compare_items[]', item.id %>
			<% end %>
		</tr>
	</table>
</div>

app/views/smartphones/_item_list_toolbox.html.erb
<div id="item-list-toolbox">
	<div class="row">
		<div class="span12">
			<h4>Listado de elementos seleccionados para comparación</h4>
			<div class="row">
				<% session[:selected_items].each do |item|%>
					<div class="span2">
						<div class="toolbox-item">
							<div class="thumbnail">
								<table>
									<tr>
										<td><%= image_tag item.img_ref %></td>
									</tr>
									<tr>
										<td><%= Marca.find(item.marca_id).nombre_marca + ' ' + item.modelo%></td>
									</tr>
									<tr>
										<td><%= number_to_currency(item.precio, :unit => '$', :precision => 0)%></td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/smartphones/_selected_items_toolbar.html.erb
<div id="bottom_toolbar">
	<div class="container">
		
		<%= render :partial => 'item_list_toolbox'%>
		
		<div id="toolbar">
			<div class="row">
				<div class="span2 offset3">
					<div id="selected_items">
							<p>Lista de comparación</p>
					</div>
				</div>
				<div class="span2">
					<%= render :partial => 'compare_list_marks'%>
				</div>
				<div class="span1">
					<%= submit_tag 'Comparar', :class => 'btn'%>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/smartphones/_smartphones_table.html.erb
<div id="smartphones_table">
	<table class="table product-table">
		<thead>
			<th></th>
			<th></th>
			<th>Imagen</th>
			<th>Marca</th>
			<th>Modelo</th>
			<th>Duración llamadas</th>
			<th>Pantalla</th>
			<th>Calidad Cámara</th>
			<th>Precio de Referencia</th>
		</thead>
		<tbody>
			<% if !@smartphones.empty? %>
				<% @smartphones.each do |smartphone|%>
					<tr>
						<td><%= hidden_field_tag 'product[]', 'd-'+ smartphone.id.to_s%></td>
						<td><%= check_box_tag 'product[]', 'a-'+ smartphone.id.to_s, session[:selected_items].detect{|item| item.id == smartphone.id} , :onclick => "$('#select_products_form').submit();" %></td>
						<td><%= link_to (image_tag smartphone.img_ref, :size => '120x120'), smartphone %></td>
						<td><%= link_to Marca.find(smartphone.marca_id).nombre_marca, smartphone %></td>
						<td><%= smartphone.modelo.upcase %></td>
						<td><%= DisplaySize.find(smartphone.display_size_id).size%></td>
						<td><%= smartphone.cam_resolution.to_s%></td>
						<td><%= number_to_currency(smartphone.precio, :unit => '$', :precision => 0) %></td>
					</tr>
				<% end %>
			<% else %>
				<td colspan="9">No se ha podido encontrar productos con las caracteristicas requeridas</td>
			<% end %>
		</tbody>
	</table>
</div>

app/views/smartphones/search.html.erb
<div class="container">
	<h1>Ando Viendo - Smartphones</h1>
	<div class="row">
		<div class="span3">
			<div class="well sidebar-nav">
				<h4>Detalles de Busqueda</h4>
				<%= form_for :search, :remote => true, :url => {:action => "search"}, :html => {:id => 'search_form'} do |s| %>
					<table class="table table-condensed nav-table">
						<tr>
							<th colspan="2">Marca</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :marca_id, marcas_select('smartphones','ASC'),{:prompt => 'Todas'}, {:onchange => "$('#search_form').submit()"}%></td>
						</tr>						
						<tr>
							<th colspan="2">Sistema Operativo</th>
						</tr>
						<tr>
							<td><%= s.check_box :os_all, {:checked => true, :onclick => "$('#search_form').submit()"}, 'os_all', ''%></td>
							<td>Todos</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_android, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>Android</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_blackberry, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>Balckberry</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_ios, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>iOS</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_symbian, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>Symbian</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_win_mob, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>Windows Mobile</td>
						</tr>
						<tr>
							<td><%= s.check_box :os_win_pho, :onclick => "$('#search_form').submit()", :class => 'featuring_os'%></td>
							<td>Windows Phone</td>
						</tr>
						<tr>
							<th colspan="2">Tamaño de Pantalla</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :screen_size , display_size_select('smartphones','ASC'),{:prompt => 'Todas'}, {:onchange => "$('#search_form').submit()"}%></td>
						</tr>
						<tr>
							<th colspan="2">Calidad de la cámara</th>
						</tr>
						<tr>
							<td colspan="2">								
								<label class="slider-label slider-label-left">(text-place-holder)</label>
								<label class="slider-label slider-label-right">(text-place-holder)</label>								
								<span id="label-slider-span"><label class="slider-label slider-label-medida">[pulgadas]</label></span>								
							</td>
						</tr>
						<tr>							
							<td colspan="2"><div id="slider-range"></div></td>
						</tr>
						<tr>
							<th>Redes</th>
						</tr>
						<tr>
							<td colspan="2">Aca va a ir lo de las redes del smartphone</td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
		<div class="span9">
			<%= form_tag select_for_compare_smartphones_path, :remote => true, :id => 'select_products_form' do %>
				<%= render :partial => 'smartphones_table'%>
			<% end %>
		</div>
	</div>
	<%= form_tag compare_smartphones_path do %>
		<%= render :partial => 'selected_items_toolbar'%>
	<% end %>
</div>