config/routes.rb
Cotizar::Application.routes.draw do

  resources :cars
  resources :computers do
    collection do
      post 'index'
      get 'alternative_new' #metodo alternativo de ingreso de computadores
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  match 'computers/:id/edit' => 'computers#edit'

  resources :televisions do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  
  resources :main
  resources :smartphones do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
    end
  end

  
  
  
  get "cars/index"
  match 'cars/save' => 'cars#save'
  match 'cars/delete' => 'cars#delete'
  match 'cars/edit' => 'cars#edit'
  match 'cars/new' => 'cars#new'
  match 'cars/update' => 'cars#update'
  match 'cars/search' => 'cars#search'
  get "main/index"

  
  root :to => 'main#index'

end

app/models/computer.rb
class Computer < ActiveRecord::Base
	belongs_to :computers_bluetooth
  belongs_to :computers_category
	belongs_to :marca
  belongs_to :computers_memoria
	belongs_to :computers_proce

	belongs_to :computers_so
  belongs_to :computers_wifi

  has_many :map_computer_aditional_features
  has_many :computer_aditional_features, through: :map_computer_aditional_features
	
  attr_accessible :img_ref, :marca_id, :modelo, :categoria, :sist_operativo_id, :precio, :bateria, :bateria_celdas, :bateria_duracion
  attr_accessible :proce_marca_id, :proce_version, :proce_velocidad, :proce_nucleos
  attr_accessible :memoria, :memoria_tipo, :memoria_velocidad, :memoria_max, :memoria_ranuras
  attr_accessible :disco_capacidad, :disco_velocidad, :disco_ssd, :screen_size, :screen_resol, :screen_type
  attr_accessible :lector_blue_ray, :grabador_blue_ray, :lector_dvd, :grabador_dvd
  attr_accessible :video_modelo, :video_memoria, :video_tipo_memoria, :webcam, :lector_tarjeta_memoria
  attr_accessible :ethernet, :hdmi, :vga, :wifi, :bluetooth, :usb_2, :usb_3, :largo, :ancho, :profundidad
  attr_accessible :id, :peso, :screen_touch
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  #layout 'products_layout'
  helper_method :sort_column, :sort_direction

  def index
    session[:compare_category] = 'computadores'
    session[:selected_items] ||= []
    if params[:search]
      @computers = search(params)
    else
      @computers = Computer.find(:all, :limit => 20)
    end

    respond_to do |format|
      format.js #search.js.erb
      format.html
    end
  end
  
  def show
    @computer = Computer.find(params[:id])

    #Lista de imagenes correspondientes a un producto
    #se considera un default de 4 imagenes por producto
    @image_paths = []
    marca = Marca.find(@computer.marca_id).nombre_marca
    modelo = @computer.modelo.upcase
    (1..4).each do |image|
      img_path = 'computer_images/'+marca+'/'+modelo+'/'+image.to_s+'.jpg'
      if File.exist?(Rails.root.join('app','assets','images', img_path))
        @image_paths << img_path
      end
    end
  end
  
  def select_for_compare
    
    params[:product].each do |product|
      action, id = product.split('-')
      
      if session[:compare_category] != 'computadores'
        session[:compare_category] = 'computadores'
        session.delete(:selected_items)
      end
          
      case action
        when 'a'
          (session[:selected_items] ||= []) << Computer.find(:first, :select => 'id, img_ref, marca_id, modelo, precio', :conditions => {:id => id})#id.to_i
        when 'd'
          if session[:selected_items].nil?
            session[:selected_items] = []
          else
            session[:selected_items].delete_if{|x| x.id == id.to_i}
          end
      end
    end
    
    respond_to do |format|
      format.js
    end
  end
  
  def compare
    @selected_items = []
    
    @items_to_compare = params[:compare_items].length
    
    params[:compare_items].each do |item|
      @selected_items << Computer.find(:first, :conditions => {:id => item})
    end
  end

  def new
    if params[:marca_id]
      @computers = Computer.find(:all, :conditions => {:marca_id => params[:marca_id][:value]})
    else
      @computers = Computer.find(:all)
    end
    @aditional_features = ComputerAditionalFeature.find(:all)
    @computer = Computer.new # Nuevo registro a ingresar    
  end

  def new_feature
    @feature = ComputerAditionalFeature.new(params[:new_feature])
    if @feature.save
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end

  def alternative_new
    #Metodo de inserción de usuarios alternativo
    @aditional_features = ComputerAditionalFeature.find(:all)
    @computer = Computer.new # Nuevo registro a ingresar
  end
  
  def create
    @computer = Computer.new(params[:computer])
    #Incluir los tipos de dato
    if @computer.bateria_duracion != ''
      @computer.bateria_duracion = @computer.bateria_duracion + " " + params[:batery_life]
    end
    if @computer.proce_velocidad != ''
      @computer.proce_velocidad = @computer.proce_velocidad + " " + params[:proce_speed]
    end
    if @computer.memoria != ''
      @computer.memoria = @computer.memoria + " " + params[:ram_storage]
    end
    if @computer.memoria_velocidad != ''
      @computer.memoria_velocidad = @computer.memoria_velocidad + " " + params[:ram_speed]
    end
    if @computer.memoria_max != ''
      @computer.memoria_max = @computer.memoria_max + " " + params[:ram_max_storage]
    end
    if @computer.disco_capacidad != ''
      @computer.disco_capacidad = @computer.disco_capacidad + " " + params[:disc_storage]
    end
    if @computer.disco_velocidad != ''
      @computer.disco_velocidad = @computer.disco_velocidad + " " + params[:disc_speed]
    end
    if @computer.disco_ssd != ''
      @computer.disco_ssd = @computer.disco_ssd + " " + params[:disc_ssd_storage]
    end
    if @computer.video_memoria.to_s != ''
      @computer.video_memoria = @computer.video_memoria + " " + params[:video_storage]
    end

    if @computer.save
      new_computer = Computer.find(:last)
      
      params[:features].each do |feature|
        action, id = feature.split('-')
        case action
        when 'a'
          MapComputerAditionalFeature.create(:computer_id => new_computer.id, :computer_aditional_feature_id => id)
        end
      end
      
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end

  def edit
    @aditional_features = ComputerAditionalFeature.find(:all)

    @computer = Computer.find(params[:id])
  end
  
  def update
    @computer = Computer.find(params[:id])
    if @computer.update_attributes(params[:computer])

      params[:features].each do |feature|
        action, id = feature.split('-')
        case action
        when 'a'
          if MapComputerAditionalFeature.where('computer_id = ? AND computer_aditional_feature_id = ?',@computer.id, id).empty?
            MapComputerAditionalFeature.create(:computer_id => @computer.id, :computer_aditional_feature_id => id)
          end
        when 'd'
          MapComputerAditionalFeature.where('computer_id = ? AND computer_aditional_feature_id = ?',@computer.id, id).destroy_all
        end
      end
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end
  
  def destroy
    if Computer.destroy(params[:id])
      redirect_to :action => 'new'
    else
      redirect_to :action => 'error'
    end
  end

  private

  def search params = {}
    
    computers = sort(params[:search][:sort], params[:search][:direction])
    
    #FILTRO POR CATEGORIA
    if params[:search][:category] == "any"
      #no se hace nada
    else
      computers = computers.select{|s| s.categoria == params[:search][:category]}
    end
    
    #FILTRO POR MARCA DE PROCESADOR
    if params[:search][:proce_id] == "any"
      #no se hace nada
    else
      computers = computers.select{|s| s.proce_marca_id.to_s == params[:search][:proce_id]}
    end
  
    #FILTRO POR MARCA
    if params[:search][:marca_id] != ""
      computers = computers.select{|s| s.marca_id.to_s == params[:search][:marca_id]}
    end
    
    #FILTRO POR TAMAÑO DE PANTALLA
    if params[:search][:screen_size] != ""
      computers = computers.select{|s| s.screen_size.to_s == params[:search][:screen_size]}
    end
    
    #FILTRO POR SISTEMA OPERATIVO
    if params[:search][:sist_operativo_id] != ""
      computers = computers.select{|s| s.sist_operativo_id.to_s == params[:search][:sist_operativo_id]}
    end
    

    #entregar los primeros 20 resultados
    computers = computers.first(20)
  end

  def sort(column, direction)
    #sort by column
    categoria = Categoria.where(:nombre => 'computadores')
    case column
    when 'marca_id'
      computers = Computer.find_by_sql("SELECT * FROM computers, marcas WHERE computers.marca_id = marcas.id ORDER BY marcas.nombre_marca "+ direction) 
    when 'categoria'
      computers = Computer.find_by_sql("SELECT * FROM computers, computers_categories WHERE computers.categoria = computers_categories.id ORDER BY computers_categories.category " + direction)
    when 'modelo'
      computers = Computer.find(:all, :order => 'modelo ' + direction)
    when 'screen_size'
      computers = Computer.find_by_sql("SELECT * FROM computers, display_sizes WHERE computers.screen_size = display_sizes.id ORDER BY display_sizes.size " + direction)
    when 'precio'
      computers = Computer.find(:all, :order => 'precio ' + direction)
    else
      computers = Computer.find_by_sql("SELECT * FROM computers, marcas WHERE computers.marca_id = marcas.id ORDER BY marcas.nombre_marca ASC") 
    end
  end

  def sort_column
    if params[:search]
      Computer.column_names.include?(params[:search][:sort]) ? params[:search][:sort] : "marca_id"
    else
      'marca_id'
    end
  end

  def sort_direction
    if params[:search]
      %w[asc desc].include?(params[:search][:direction]) ? params[:search][:direction] : "asc"
    else
      'asc'
    end
  end
end

app/helpers/computers_helper.rb
module ComputersHelper

	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = column == sort_column ? "current #{sort_direction}" : nil
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		#"<span class='product-table-title' sort='"+column+"' drct='"+direction+"'>"+title+"</span>"
		link_to title, '#' , :onclick => "sort_column('"+column+"','"+direction+"');"
	end

	def feature_check(computer, feature)
		if computer.id
			if MapComputerAditionalFeature.where('computer_id = ? and computer_aditional_feature_id = ?', computer.id, feature).empty?
				return false
			else
				return true
			end
		else
			return false
		end
	end

	def select_options(type)
		case type
		when 'boolean'
			return [["Si",1], ["No",0], ["No Especificado",]]
		end
	end

	def data_type_select(feature)
		case feature
		when 'batery_life'
			return options_for_select({"Horas" => "Hrs", "-" => ""}, "Hrs")
		when 'proce_speed'
			return options_for_select({"MHz" => "MHz", "GHz" => "GHz", "-" => ""}, "GHz")
		when 'disc_storage'
			return options_for_select({"GB" => "GB", "TB" => "TB", "-" => ""}, "GB")
		when 'disc_speed'
			return options_for_select({"RPM" => "RPM", "-" => ""}, "RPM")
		when 'ram_storage'
			return options_for_select({"MB" => "MB", "GB" => "GB", "-" => ""}, "GB")
		when 'ram_speed'
			return options_for_select({"MHz" => "MHz", "GHz" => "GHz", "-" => ""}, "MHz")
		end
	end
end

app/views/computers/_aditional_features.html.erb
<tr>
	<th colspan="2">Catacterísticas Adicionales</th>
</tr>
<% @aditional_features.each do |a| %>
<tr>
	<td><%= a.feature%></td>
	<%= hidden_field_tag 'features[]', 'd-'+a.id.to_s%>

	<td><%= check_box_tag 'features[]', 'a-'+a.id.to_s, feature_check(@computer,a.id)%></td>
</tr>
<%end%>

app/views/computers/index.html.erb
<div class="container">
	<h1>Ando Viendo - Computadores</h1>
	<div class="row">
		<div class="span3">
			<div class="well sidebar-nav">
				<h4>Detalles de Busqueda</h4>
				<%= form_for :search, :remote => true, :url => {:action => "index"}, :html => {:id => 'search_form'} do |s| %>
					<table class="table table-condensed nav-table">
						<%= s.hidden_field :sort, :value => 'marca_id', :id => 'sort_field'%>
						<%= s.hidden_field :direction, :value => 'asc', :id => 'direction_field'%>
						<tr>
							<th colspan="2">Categoria</th>
						</tr>
						<tr>
							<td><%= s.radio_button :category, :any, :checked => true, :class => 'product_ft'%></td>
							<td>Todas</td>
						</tr>
						<tr>
							<td><%= s.radio_button :category, 1, :class => 'product_ft'%></td>
							<td>All In One</td>
						</tr>
						<tr>
							<td><%= s.radio_button :category, 2, :class => 'product_ft'%></td>
							<td>Notebook</td>
						</tr>
						<tr>
							<td><%= s.radio_button :category, 3, :class => 'product_ft'%></td>
							<td>Ultrabook</td>
						</tr>
						<tr>
							<td><%= s.radio_button :category, 4, :class => 'product_ft'%></td>
							<td>Netbook</td>
						</tr>
						<tr>
							<td><%= s.radio_button :category, 5, :class => 'product_ft'%></td>
							<td>Desktop</td>
						</tr>
						<tr>
							<th colspan="2">Procesador</th>
						</tr>
						<tr>
							<td><%= s.radio_button :proce_id, :any, :checked => true, :class => 'product_ft'%></td>
							<td>Todas</td>
						</tr>
						<tr>
							<td><%= s.radio_button :proce_id, 1, :class => 'product_ft'%></td>
							<td>AMD</td>
						</tr>
						<tr>
							<td><%= s.radio_button :proce_id, 2, :class => 'product_ft'%></td>
							<td>Intel</td>
						</tr>
						<tr>
							<th colspan="2">Marca</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :marca_id, marcas_select('computadores','ASC'),{:prompt => 'Todas'}, {:class => 'product_ft_select'}%></td>
						</tr>
						<tr>
							<th colspan="2">Tamaño de Pantalla</th>
						</tr>
						<tr>
								<td colspan="2"><%= s.select :screen_size , display_size_select('computadores', 'ASC'),{:prompt => 'Todas'}, {:class => 'product_ft_select'}%></td>
						</tr>
						<tr>
							<th colspan="2">Sistema Operativo</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :sist_operativo_id, ComputersSo.all.collect{|m| [m.sist_operativo, m.id]},{:prompt => 'Todos'}, {:class => 'product_ft_select'}%></td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
		<div class="span9">
			<%= form_tag select_for_compare_computers_path, :remote => true, :id => 'select_products_form' do %>
				<%= render :partial => 'computers_table'%>
			<% end %>
		</div>
	</div>
	<%= form_tag compare_computers_path do %>
		<%= render :partial => 'selected_items_toolbar'%>
	<% end %>
</div>

app/views/computers/index.js.erb
$("#computers_table").replaceWith("<%= escape_javascript(render(:partial => "computers_table"))%>");

app/views/computers/new.html.erb
<div class="container">	
	<h1>Ingresar Nuevos Computadores</h1>
	<%= form_for :marca_id, :url => new_computer_path do |fl| %>
		<table class="table">
			<tr>
				<th>Buscar por Marca</th>
				<td><%= fl.select 'value', marcas_select('computadores', 'ASC')%></td>
				<td><%= submit_tag 'Buscar', :class => 'btn'%></td>
			</tr>
		</table>
	<% end %>
	<%= link_to "Alternativa", alternative_new_computers_path %>
	
	<table class="table table-bordered">
		<% @aditional_features.each do |ft| %>
		<tr>
			<td><%= ft.feature%></td>
		</tr>
		<% end %>
		
		<%= form_for :new_feature, :url => new_feature_computers_path do |f|%>
		<tr>
			<td><%= f.text_field :feature, :placeholder => 'Nueva Caracteristica' %></td>
		</tr>
		<tr>
			<td><%= f.submit 'Agregar Caracteristica', :class => 'btn'%></td>
		</tr>
		<% end %>
	</table>
	
	<table class="table table-bordered table-striped input-table">
		<thead>
			<tr>
				<th>Delete</th>
				<th>Edit</th>
				<th>Preview Image</th>
				<th>Imagen</th>
				<th>Marca</th>
				<th>Categoría</th>
				<th>Modelo</th>
				<th>Sistema Operativo</th>
				<th>Precio</th>
				<th>Material Batería</th>
				<th>N° Celdas Batería</th>
				<th>Duración Bateria</th>
				<th>Marca Procesador</th>
				<th>Versión Procesador</th>
				<th>Velocidad Procesador [GHz]</th>
				<th>N° Núcleos</th>
				<th>Cantidad Memoria [GB]</th>
				<th>Tipo Memoria</th>
				<th>Velocidad Memoria [MHz]</th>
				<th>Máximo Memoria [GB]</th>
				<th>N° Ranuras Memoria</th>
				<th>Capacidad Disco Duro [GB]</th>
				<th>Velocidad Disco Duro [RPM]</th>
				<th>Disco Duro SSD [GB]</th>
				<th>Tamaño Pantalla [in]</th>
				<th>Resolución</th>
				<th>Tipo Pantalla</th>
				<th>Pantalla Touch</th>
				<th>Lector Blue-Ray</th>
				<th>Grabador Blue-Ray</th>
				<th>Lector DVD</th>
				<th>Grabador DVD</th>
				<th>Tarjeta de Video</th>
				<th>Cantidad Memoria T. Video</th>
				<th>Tipo de Memoria T.Video</th>
				<th>Webcam</th>
				<th>Lector Tarjetas de Memoria</th>
				<th>Ethernet</th>
				<th>HDMI</th>
				<th>VGA</th>
				<th>Wi-Fi</th>
				<th>Bluetooth</th>
				<th>USB 2.0</th>
				<th>USB 3.0</th>
				<th>Largo [mm]</th>
				<th>Ancho [mm]</th>
				<th>Alto [mm]</th>
				<th>Peso [kg]</th>
				<th>Guardar</th>
			</tr>
		</thead>
		<tbody>
			<% if !@computers.empty? %>
				<% @computers.each do |computer|%>
			
					<tr>
						<td><%= button_to 'Delete', computer, :confirm => 'Segurito?', :method => 'delete', :class => 'btn'%></td>
						<td><%= button_to 'Edit', edit_computer_path(computer), :class => 'btn'%></td>
						<td><%= image_tag computer.img_ref, :size => '120x120'%></td>
						<td><%= image_tag computer.img_ref, :size => '120x120'%></td>
						<td><%= Marca.find(computer.marca_id).nombre_marca%></td>
						<td><%= ComputersCategory.find(computer.categoria).category%></td>
						<td><%= computer.modelo.upcase %></td>
						<td><%= ComputersSo.find(computer.sist_operativo_id).sist_operativo%></td>
						<td><%= computer.precio%></td>
						<td><%= computer.bateria%></td>
						<td><%= computer.bateria_celdas%></td>
						<td><%= computer.bateria_duracion%></td>
						<td><%= ComputersProce.find(computer.proce_marca_id).marca%></td>
						<td><%= computer.proce_version%></td>
						<td><%= computer.proce_velocidad%></td>
						<td><%= computer.proce_nucleos%></td>
						<td><%= computer.memoria%></td>
						<td><%= ComputersMemoria.find(computer.memoria_tipo).tipo%></td>
						<td><%= computer.memoria_velocidad%></td>
						<td><%= computer.memoria_max%></td>
						<td><%= computer.memoria_ranuras%></td>
						<td><%= computer.disco_capacidad%></td>
						<td><%= computer.disco_velocidad%></td>
						<td><%= computer.disco_ssd%></td>
						<td><%= DisplaySize.find(computer.screen_size).size%></td>
						<td><%= DisplayResolution.find(computer.screen_resol).resolution%></td>
						<td><%= DisplayTech.find(computer.screen_type).nombre%></td>
						<td><%= computer.screen_touch%></td>
						<td><%= computer.lector_blue_ray%></td>
						<td><%= computer.grabador_blue_ray%></td>
						<td><%= computer.lector_dvd%></td>
						<td><%= computer.grabador_dvd%></td>
						<td><%= computer.video_modelo%></td>
						<td><%= computer.video_memoria%></td>
						<td><%= ComputersMemoria.find(computer.video_tipo_memoria).tipo%></td>
						<td><%= computer.webcam%></td>
						<td><%= computer.lector_tarjeta_memoria%></td>
						<td><%= computer.ethernet%></td>
						<td><%= computer.hdmi%></td>
						<td><%= computer.vga%></td>
						<td><%= RedProtocol.find(computer.wifi).nombre%></td>
						<td><%= RedProtocol.find(computer.bluetooth).nombre%></td>
						<td><%= computer.usb_2%></td>
						<td><%= computer.usb_3%></td>
						<td><%= computer.largo%></td>
						<td><%= computer.ancho%></td>
						<td><%= computer.profundidad%></td>
						<td><%= computer.peso%></td>
						<td> </td>
					</tr>
				<% end %>
			<% else %>
			<tr>
				<td colspan="44">No se encontró información relacionada con los parametros seleccionados</td>
			</tr>
			<% end %>
			
			<%= form_for(@computer) do |c|%>
				<tr>
					<td><%= link_to "Alternativa", alternative_new_computers_path %></td>
					<td><%= link_to "Edit", cars_new_path, :class => "btn", :disabled => "disabled" %></td>
					<td><div id="new-product-img-preview"><%= image_tag 'computer_images/not_found.png', :size => '100x100'%></div></td>
					<td><%= c.text_field :img_ref, :value => 'computer_images/not_found.png', :id => 'new_product_img'%></td>
					<td><%= c.select :marca_id, marcas_select('computadores', 'ASC')%></td>
					<td><%= c.select :categoria, ComputersCategory.all.collect{|c| [c.category, c.id]}, {:selected => 2}%></td>
					<td><%= c.text_field :modelo, :value => ''%></td>
					<td><%= c.select :sist_operativo_id, ComputersSo.all.collect{|s| [s.sist_operativo, s.id]}, {:selected => 1}%></td>
					<td><%= c.text_field :precio, :value => ''%></td>
					<td><%= c.text_field :bateria, :valie => ' '%></td>
					<td><%= c.select :bateria_celdas, options_for_select(select_options('numbers'),4)%></td>
					<td><%= c.text_field :bateria_duracion, :value => ''%></td>
					<td><%= c.select :proce_marca_id, ComputersProce.all.collect{|p| [p.marca, p.id]}, {:selected => 2}%></td>
					<td><%= c.text_field :proce_version, :value => ''%></td>
					<td><%= c.text_field :proce_velocidad, :value => ''%></td>
					<td><%= c.select :proce_nucleos, options_for_select(select_options('numbers'), 2)%></td>
					<td><%= c.select :memoria, options_for_select(select_options('numbers'), 4)%></td>
					<td><%= c.select :memoria_tipo, ComputersMemoria.all.collect{|m| [m.tipo, m.id]}, {:selected => 3}%></td>
					<td><%= c.text_field :memoria_velocidad, :value => ''%></td>
					<td><%= c.select :memoria_max, options_for_select(select_options('numbers'), 4)%></td>
					<td><%= c.select :memoria_ranuras, options_for_select(select_options('numbers'), 2)%></td>
					<td><%= c.text_field :disco_capacidad, :value => ''%></td>
					<td><%= c.text_field :disco_velocidad, :value => ''%></td>
					<td><%= c.text_field :disco_ssd, :value => ''%></td>
					<td><%= c.select :screen_size, display_size_select('computadores', 'ASC')%></td>
					<td><%= c.select :screen_resol, DisplayResolution.find(:all, :order => 'resolution ASC').collect{|r| [r.resolution, r.id]}%></td>
					<td><%= c.select :screen_type, display_tech_select('computadores', 'ASC')%></td>
					<td><%= c.select :screen_touch, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :lector_blue_ray, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :grabador_blue_ray, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :lector_dvd, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :lector_dvd, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.text_field :video_modelo, :value => ''%></td>
					<td><%= c.text_field :video_memoria, :placeholder => '[MB/GB]'%></td>
					<td><%= c.select :video_tipo_memoria, ComputersMemoria.all.collect{|m| [m.tipo,m.id]}, {:selected => 5}%></td>
					<td><%= c.select :webcam, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.text_field :lector_tarjeta_memoria %></td>
					<td><%= c.select :ethernet, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :hdmi, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :vga, options_for_select(select_options('boolean'),0)%></td>
					<td><%= c.select :wifi, red_select('wifi')%></td>
					<td><%= c.select :bluetooth, red_select('bluetooth')%></td>
					<td><%= c.select :usb_2, options_for_select(select_options('numbers'),1)%></td>
					<td><%= c.select :usb_3, options_for_select(select_options('numbers'),1)%></td>
					<td><%= c.text_field :largo, :value => ''%></td>
					<td><%= c.text_field :ancho, :value => ''%></td>
					<td><%= c.text_field :profundidad, :value => ''%></td>
					<td><%= c.text_field :peso, :value => ''%></td>
					<td><%= c.submit :class => 'btn'%></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/computers/search.js.erb
$("#computers_table").replaceWith("<%= escape_javascript(render(:partial => "computers_table"))%>");