config/routes.rb
Cotizar::Application.routes.draw do

  resources :cars
  resources :computers do
    collection do
      post 'index'
      get 'alternative_new' #metodo alternativo de ingreso de computadores
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  match 'computers/:id/edit' => 'computers#edit'

  resources :televisions do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
      post 'new_feature'
    end
  end
  
  resources :main
  resources :smartphones do
    collection do
      get 'index'
      post 'search'
      post 'select_for_compare'
      post 'compare'
      post 'compare_toolbox'
    end
  end

  
  
  
  get "cars/index"
  match 'cars/save' => 'cars#save'
  match 'cars/delete' => 'cars#delete'
  match 'cars/edit' => 'cars#edit'
  match 'cars/new' => 'cars#new'
  match 'cars/update' => 'cars#update'
  match 'cars/search' => 'cars#search'
  get "main/index"

  
  root :to => 'main#index'

end

app/models/television.rb
class Television < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/televisions_controller.rb
class TelevisionsController < ApplicationController

	def index 
		@televisions = Television.find(:all)
		session[:compare_category] = 'televisores'
		session[:selected_items] ||= []
		render :search
	end

	def show
		@television = Television.find(params[:id])

		@image_paths = []

		marca = Marca.find(@television.marca_id).nombre_marca
		modelo = @television.modelo.upcase
		(1..4).each do |image|
			img_path = 'television_images/'+marca+'/'+modelo+'/'+image.to_s+'.jpg'
			if File.exists?(Rails.root.join('app','assets','images', img_path))
				@image_paths << img_path
			end
		end
	end

	def select_for_compare
	    params[:product].each do |product|
	      action, id = product.split('-')
	      
	      if session[:compare_category] != 'televisores'
	        session[:compare_category] = 'televisores'
	        session.delete(:selected_items)
	      end
	          
	      case action
	        when 'a'
	          (session[:selected_items] ||= []) << Television.find(:first, :select => 'id, img_ref, marca_id, modelo, precio', :conditions => {:id => id})#id.to_i
	        when 'd'
	          if session[:selected_items].nil?
	            session[:selected_items] = []
	          else
	            session[:selected_items].delete_if{|x| x.id == id.to_i}
	          end
	      end
	    end
	    
	    respond_to do |format|
	      format.js
	    end
	end

	def compare
	    @selected_items = []
	    
	    @items_to_compare = params[:compare_items].length
	    
	    params[:compare_items].each do |item|
	      @selected_items << Television.find(:first, :conditions => {:id => item})
	    end
	end
end

app/helpers/televisions_helper.rb
module TelevisionsHelper
end

app/views/televisions/_televisions_table.html.erb
<div id="televisions_table">
	<table class="table product-table">
		<thead>
			<th></th>
			<th></th>
			<th>Imagen</th>
			<th>Marca</th>
			<th>Modelo</th>
			<th>Tecnología</th>
			<th>Tamaño</th>
			<th>Precio de Referencia</th>
		</thead>
		<tbody>
			<% if !@televisions.empty? %>
				<% @televisions.each do |television|%>
					<tr>
						<td><%= hidden_field_tag 'product[]', 'd-'+television.id.to_s%></td>
						<td><%= check_box_tag 'product[]', 'a-'+television.id.to_s, session[:selected_items].detect{|item| item.id == television.id} , :onclick => "$('#select_products_form').submit();" %></td>
						<td><%= link_to (image_tag television.img_ref, :size => '120x120'), television %></td>
						<td><%= link_to Marca.find(television.marca_id).nombre_marca, television %></td>
						<td><%= television.modelo.upcase%></td>
						<td><%= DisplayTech.find(television.display_tech).nombre%></td>
						<td><%= DisplaySize.find(television.display_size_id).size%></td>
						<td><%= number_to_currency(television.precio, :unit => '$', :precision => 0) %></td>
					</tr>
				<% end %>
			<% else %>
				<td colspan="8">No se ha podido encontrar productos con las caracteristicas requeridas</td>
			<% end %>
		</tbody>
	</table>
</div>

app/views/televisions/search.html.erb
<div class="container">
	<h1>Ando Viendo - Televisores</h1>
	<div class="row">
		<div class="span3">
			<div class="well sidebar-nav">
				<h4>Detalles de Busqueda</h4>
				<%= form_for :search, :remote => true, :url => {:action => "search"}, :html => {:id => 'search_form'} do |s| %>
					<table class="table table-condensed nav-table">
						<tr>
							<th colspan="2">Tecnología</th>
						</tr>
						<tr>
							<td><%= s.check_box :tech_all, {:checked => true, :onclick => "$('#search_form').submit()"}, 'tech_all', ''%></td>
							<td>Todas</td>
						</tr>
						<tr>
							<td><%= s.check_box :tech_led,{:onclick => "$('#search_form').submit()"}, 1, ''%></td>
							<td>LED</td>
						</tr>
						<tr>
							<td><%= s.check_box :tech_lcd,{:onclick => "$('#search_form').submit()"}, 2, ''%></td>
							<td>LCD</td>
						</tr>
						<tr>
							<td><%= s.check_box :tech_plasma,{ :onclick => "$('#search_form').submit()"}, 6, ''%></td>
							<td>Plasma</td>
						</tr>
						<tr>
							<th colspan="2">Tamaño de Pantalla</th>
						</tr>
						<tr>
							<td>Mínimo</td>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :display_size_min, display_size_select('televisores', 'ASC'), {:onclick => "$('#search_form').submit()"}%></td>
						</tr>
						<tr>
							<td>Máximo</td>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :display_size_max, display_size_select('televisores', 'DESC'), {:onclick => "$('#search_form').submit()"}%></td>
						</tr>
						<tr>
							<th colspan="2">Marca</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :marca_id, marcas_select('televisores','ASC'),{:prompt => 'Todas'}, {:onchange => "$('#search_form').submit()"}%></td>
						</tr>
						<tr>
							<th colspan="2">Tamaño de Pantalla</th>
						</tr>
						<tr>
							<td colspan="2"><%= s.select :screen_size , display_size_select('televisores','ASC'),{:prompt => 'Todas'}, {:onchange => "$('#search_form').submit()"}%></td>
						</tr>
					</table>
				<% end %>
			</div>
		</div>
		<div class="span9">
			<!-- Tabla de televisores -->
			<%= form_tag select_for_compare_televisions_path, :remote => true, :id => 'select_products_form' do %>
				<%= render :partial => 'televisions_table'%>
			<% end %>
		</div>
	</div>
	<!-- Bottom Toolbar -->
	<%= form_tag compare_televisions_path do %>
		<%= render :partial => 'selected_items_toolbar'%>
	<% end %>
</div>

app/views/televisions/search.js.erb
$("#televisions_table").replaceWith("<%= escape_javascript(render(:partial => "televisions_table"))%>");

app/views/televisions/select_for_compare.js.erb
$("#compare-list-marks").replaceWith("<%= escape_javascript(render(:partial => "compare_list_marks"))%>");
$("#item-list-toolbox").replaceWith("<%= escape_javascript(render(:partial => "item_list_toolbox"))%>");